CREATE TABLE IF NOT EXISTS `t_catalog_config` (
  `category` varchar(191) NOT NULL,
  `type` varchar(30) NOT NULL,
  `source` varchar(30) NOT NULL,
  `slug` varchar(191) NOT NULL,
  `order` int DEFAULT NULL,
  `name` varchar(191) DEFAULT NULL,
  `configuration` longtext DEFAULT NULL,
  PRIMARY KEY (`category`,`type`,`source`,`slug`)
);

INSERT INTO t_catalog_config (`category`, `type`, `source`, `slug`, `order`) VALUES
    ('WHISKY','catalog','taxons','country','0'),
    ('WHISKY','catalog','properties','ptype','1'),
    ('WHISKY','catalog','properties','age','2'),
    ('WHISKY','catalog','properties','vintage','3'),
    ('WHISKY','catalog','taxons','brand','4'),
    ('WHISKY','catalog','properties','syre','5'),
    ('WHISKY','catalog','properties','Aging_in_barrels','6'),
    ('WHISKY','catalog','properties','filtering','7'),
    ('WHISKY','catalog','properties','strength','8'),
    ('WHISKY','catalog','properties','pval','9'),
    ('WHISKY','catalog','properties','pack','10'),
    ('WHISKY','menu','taxons','country','0'),
    ('WHISKY','menu','properties','ptype','1'),
    ('WHISKY','menu','properties','age','2'),
    ('WHISKY','menu','properties','pack','3'),
    ('WHISKY','menu','taxons','brand','4'),
    ('WHISKY','filters','taxons','brand','0'),
    ('WHISKY','filters','taxons','country','1'),
    ('WHISKY','filters','properties','ptype','2'),
    ('WHISKY','filters','properties','age','3'),
    ('WHISKY','filters','properties','vintage','4'),
    ('WHISKY','filters','properties','syre','6'),
    ('WHISKY','filters','properties','Aging_in_barrels','7'),
    ('WHISKY','filters','properties','filtering','8'),
    ('WHISKY','filters','properties','strength','9'),
    ('WHISKY','filters','properties','pval','10'),
    ('WHISKY','filters','properties','pack','11'),
    ('COGNAC-ALL','catalog','taxons','category','0'),
    ('COGNAC-ALL','catalog','taxons','country','1'),
    ('COGNAC-ALL','catalog','properties','pclass','2'),
    ('COGNAC-ALL','catalog','properties','age','3'),
    ('COGNAC-ALL','catalog','taxons','brand','4'),
    ('COGNAC-ALL','catalog','properties','vintage','5'),
    ('COGNAC-ALL','catalog','properties','strength','6'),
    ('COGNAC-ALL','catalog','properties','pval','7'),
    ('COGNAC-ALL','catalog','properties','pack','8'),
    ('COGNAC-ALL','menu','taxons','category','0'),
    ('COGNAC-ALL','menu','taxons','country','1'),
    ('COGNAC-ALL','menu','properties','pclass','2'),
    ('COGNAC-ALL','menu','properties','age','3'),
    ('COGNAC-ALL','menu','taxons','brand','4'),
    ('COGNAC-ALL','filters','taxons','brand','0'),
    ('COGNAC-ALL','filters','taxons','category','1'),
    ('COGNAC-ALL','filters','taxons','country','2'),
    ('COGNAC-ALL','filters','properties','pclass','3'),
    ('COGNAC-ALL','filters','properties','age','4'),
    ('COGNAC-ALL','filters','properties','vintage','6'),
    ('COGNAC-ALL','filters','properties','strength','7'),
    ('COGNAC-ALL','filters','properties','pval','8'),
    ('COGNAC-ALL','filters','properties','pack','9'),
    ('VODKA-ALL','catalog','taxons','category','0'),
    ('VODKA-ALL','catalog','taxons','country','1'),
    ('VODKA-ALL','catalog','properties','ptype','2'),
    ('VODKA-ALL','catalog','properties','pclass','3'),
    ('VODKA-ALL','catalog','taxons','brand','4'),
    ('VODKA-ALL','catalog','properties','taste','5'),
    ('VODKA-ALL','catalog','properties','syre','6'),
    ('VODKA-ALL','catalog','properties','strength','7'),
    ('VODKA-ALL','catalog','properties','pval','8'),
    ('VODKA-ALL','catalog','properties','pack','9'),
    ('VODKA-ALL','menu','taxons','category','0'),
    ('VODKA-ALL','menu','taxons','country','1'),
    ('VODKA-ALL','menu','properties','ptype','2'),
    ('VODKA-ALL','menu','properties','pclass','3'),
    ('VODKA-ALL','menu','taxons','brand','4'),
    ('VODKA-ALL','filters','taxons','brand','0'),
    ('VODKA-ALL','filters','taxons','category','1'),
    ('VODKA-ALL','filters','taxons','country','2'),
    ('VODKA-ALL','filters','properties','ptype','3'),
    ('VODKA-ALL','filters','properties','pclass','4'),
    ('VODKA-ALL','filters','properties','taste','6'),
    ('VODKA-ALL','filters','properties','syre','7'),
    ('VODKA-ALL','filters','properties','strength','8'),
    ('VODKA-ALL','filters','properties','pval','9'),
    ('VODKA-ALL','filters','properties','pack','10'),
    ('WINE-ALL','catalog','taxons','category','0'),
    ('WINE-ALL','catalog','taxons','country','1'),
    ('WINE-ALL','catalog','properties','color','2'),
    ('WINE-ALL','catalog','properties','sugar','3'),
    ('WINE-ALL','catalog','properties','psort','4'),
    ('WINE-ALL','catalog','properties','pyear','5'),
    ('WINE-ALL','catalog','properties','age','6'),
    ('WINE-ALL','catalog','properties','vintage','7'),
    ('WINE-ALL','catalog','properties','strength','8'),
    ('WINE-ALL','catalog','properties','pval','9'),
    ('WINE-ALL','catalog','properties','pack','10'),
    ('WINE-ALL','menu','taxons','category','0'),
    ('WINE-ALL','menu','taxons','country','1'),
    ('WINE-ALL','menu','properties','color','2'),
    ('WINE-ALL','menu','properties','sugar','3'),
    ('WINE-ALL','menu','properties','psort','4'),
    ('WINE-ALL','filters','taxons','brand','0'),
    ('WINE-ALL','filters','taxons','category','1'),
    ('WINE-ALL','filters','taxons','country','2'),
    ('WINE-ALL','filters','properties','color','3'),
    ('WINE-ALL','filters','properties','sugar','4'),
    ('WINE-ALL','filters','properties','psort','6'),
    ('WINE-ALL','filters','properties','pyear','7'),
    ('WINE-ALL','filters','properties','age','8'),
    ('WINE-ALL','filters','properties','strength','9'),
    ('WINE-ALL','filters','properties','pval','10'),
    ('WINE-ALL','filters','properties','pack','11'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','taxons','category','0'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','taxons','country','1'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','color','2'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','sugar','3'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','taxons','brand','4'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','psort','5'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','vintage','6'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','strength','7'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','pval','8'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','properties','pack','9'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','menu','taxons','category','0'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','menu','taxons','country','1'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','menu','properties','color','2'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','menu','properties','sugar','3'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','menu','taxons','brand','4'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','taxons','brand','0'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','taxons','category','1'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','taxons','country','2'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','color','3'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','sugar','4'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','psort','6'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','vintage','7'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','strength','8'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','pval','9'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','properties','pack','10'),
    ('SPIRITS','catalog','taxons','category','0'),
    ('SPIRITS','catalog','taxons','country','1'),
    ('SPIRITS','catalog','properties','ptype','2'),
    ('SPIRITS','catalog','properties','age','3'),
    ('SPIRITS','catalog','taxons','brand','4'),
    ('SPIRITS','catalog','properties','syre','5'),
    ('SPIRITS','catalog','properties','Aging_in_barrels','6'),
    ('SPIRITS','catalog','properties','strength','7'),
    ('SPIRITS','catalog','properties','pval','8'),
    ('SPIRITS','catalog','properties','pack','9'),
    ('SPIRITS','menu','taxons','category','0'),
    ('SPIRITS','menu','taxons','country','1'),
    ('SPIRITS','menu','properties','ptype','2'),
    ('SPIRITS','menu','properties','pack','3'),
    ('SPIRITS','menu','taxons','brand','4'),
    ('SPIRITS','filters','taxons','brand','0'),
    ('SPIRITS','filters','taxons','category','1'),
    ('SPIRITS','filters','taxons','country','2'),
    ('SPIRITS','filters','properties','ptype','3'),
    ('SPIRITS','filters','properties','age','4'),
    ('SPIRITS','filters','properties','syre','6'),
    ('SPIRITS','filters','properties','Aging_in_barrels','7'),
    ('SPIRITS','filters','properties','strength','8'),
    ('SPIRITS','filters','properties','pval','9'),
    ('SPIRITS','filters','properties','pack','10'),
    ('MIXOLOGY','catalog','taxons','category','0'),
    ('MIXOLOGY','catalog','taxons','country','1'),
    ('MIXOLOGY','catalog','properties','ptype','2'),
    ('MIXOLOGY','catalog','properties','taste','3'),
    ('MIXOLOGY','catalog','taxons','brand','4'),
    ('MIXOLOGY','catalog','properties','color','5'),
    ('MIXOLOGY','catalog','properties','strength','6'),
    ('MIXOLOGY','catalog','properties','pval','7'),
    ('MIXOLOGY','catalog','properties','pack','8'),
    ('MIXOLOGY','menu','taxons','category','0'),
    ('MIXOLOGY','menu','taxons','country','1'),
    ('MIXOLOGY','menu','properties','ptype','2'),
    ('MIXOLOGY','menu','properties','taste','3'),
    ('MIXOLOGY','menu','taxons','brand','4'),
    ('MIXOLOGY','filters','taxons','brand','0'),
    ('MIXOLOGY','filters','taxons','category','1'),
    ('MIXOLOGY','filters','taxons','country','2'),
    ('MIXOLOGY','filters','properties','ptype','3'),
    ('MIXOLOGY','filters','properties','taste','4'),
    ('MIXOLOGY','filters','properties','color','6'),
    ('MIXOLOGY','filters','properties','strength','7'),
    ('MIXOLOGY','filters','properties','pval','8'),
    ('MIXOLOGY','filters','properties','pack','9'),
    ('DRUGIE_NAPITKI','catalog','taxons','category','0'),
    ('DRUGIE_NAPITKI','catalog','taxons','country','1'),
    ('DRUGIE_NAPITKI','catalog','properties','ptype','2'),
    ('DRUGIE_NAPITKI','catalog','properties','taste','3'),
    ('DRUGIE_NAPITKI','catalog','taxons','brand','4'),
    ('DRUGIE_NAPITKI','catalog','properties','gazaciya','5'),
    ('DRUGIE_NAPITKI','catalog','properties','tara','6'),
    ('DRUGIE_NAPITKI','catalog','properties','tip-otzhima','7'),
    ('DRUGIE_NAPITKI','catalog','properties','pval','8'),
    ('DRUGIE_NAPITKI','catalog','properties','packval','9'),
    ('DRUGIE_NAPITKI','menu','taxons','category','0'),
    ('DRUGIE_NAPITKI','menu','taxons','country','1'),
    ('DRUGIE_NAPITKI','menu','properties','gazaciya','2'),
    ('DRUGIE_NAPITKI','menu','properties','tara','3'),
    ('DRUGIE_NAPITKI','menu','taxons','brand','4'),
    ('DRUGIE_NAPITKI','filters','taxons','brand','0'),
    ('DRUGIE_NAPITKI','filters','taxons','category','1'),
    ('DRUGIE_NAPITKI','filters','taxons','country','2'),
    ('DRUGIE_NAPITKI','filters','properties','ptype','3'),
    ('DRUGIE_NAPITKI','filters','properties','taste','4'),
    ('DRUGIE_NAPITKI','filters','properties','gazaciya','6'),
    ('DRUGIE_NAPITKI','filters','properties','tara','7'),
    ('DRUGIE_NAPITKI','filters','properties','tip-otzhima','8'),
    ('DRUGIE_NAPITKI','filters','properties','pval','9'),
    ('DRUGIE_NAPITKI','filters','properties','pack','10'),
    ('GLASS-ALL','catalog','taxons','category','0'),
    ('GLASS-ALL','catalog','taxons','country','1'),
    ('GLASS-ALL','catalog','properties','ptype','2'),
    ('GLASS-ALL','catalog','properties','naznachenie','3'),
    ('GLASS-ALL','catalog','taxons','brand','4'),
    ('GLASS-ALL','catalog','properties','production_method','5'),
    ('GLASS-ALL','catalog','properties','material','6'),
    ('GLASS-ALL','catalog','properties','color','7'),
    ('GLASS-ALL','catalog','properties','volume','8'),
    ('GLASS-ALL','catalog','properties','packval','9'),
    ('GLASS-ALL','menu','taxons','category','0'),
    ('GLASS-ALL','menu','taxons','country','1'),
    ('GLASS-ALL','menu','properties','ptype','2'),
    ('GLASS-ALL','menu','properties','naznachenie','3'),
    ('GLASS-ALL','menu','taxons','brand','4'),
    ('GLASS-ALL','filters','taxons','brand','0'),
    ('GLASS-ALL','filters','taxons','category','1'),
    ('GLASS-ALL','filters','taxons','country','2'),
    ('GLASS-ALL','filters','properties','ptype','3'),
    ('GLASS-ALL','filters','properties','naznachenie','4'),
    ('GLASS-ALL','filters','properties','production_method','6'),
    ('GLASS-ALL','filters','properties','material','7'),
    ('GLASS-ALL','filters','properties','color','8'),
    ('GLASS-ALL','filters','properties','volume','9'),
    ('GLASS-ALL','filters','properties','packval','10'),
    ('default','catalog','properties','ptype','0');
INSERT INTO t_catalog_config (`category`, `type`, `source`, `slug`, `order`, `name`, `configuration`) VALUES
    ('WHISKY','catalog','product','price','11','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('WHISKY','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('COGNAC-ALL','catalog','product','price','9','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('COGNAC-ALL','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('VODKA-ALL','catalog','product','price','10','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('VODKA-ALL','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('WINE-ALL','catalog','product','price','11','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('WINE-ALL','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','catalog','product','price','10','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('CHAMPAGNE-AND-SPARKLING-WINES','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('SPIRITS','catalog','product','price','10','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('SPIRITS','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('MIXOLOGY','catalog','product','price','9','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('MIXOLOGY','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('DRUGIE_NAPITKI','catalog','product','price','10','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('DRUGIE_NAPITKI','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('GLASS-ALL','catalog','product','price','10','Диапазон цен','{"price_steps": [1000, 3000, 6000] }'),
    ('GLASS-ALL','filters','product','price','5','Диапазон цен','{"price_steps": [1000, 3000, 6000] }');



INSERT INTO t_catalog_config (category,`type`,source,slug,`order`) VALUES
  ('_default','filters','properties','ptype', 0),
  ('_default','menu','properties','ptype', 0),
  ('_default','catalog','properties','ptype', 0);

